#!/bin/sh
############################################
# Write for  Gnu-Linux O.S.                       
# Author      : Cristian Pozzessere               
# D.A.Page    : http://lnanny.deviantart.com     
# Git Hub Page : https://github.com/ilnanny       
# Lila HD Icon Theme for Gnu/Linux O.S.         
############################################
#Lila HD Folder Colors
#e0a55a   standard
#359bfa   blue
#2e8d13   green
#dec993   kaki
#d6d6d6   ligth-gray
#4E5558   dark
#C094C0   purple
#  ===  ===  ===  ===  ===  ===  ===
#Change color from blue to purple:
#  ===  ===  ===  ===  ===  ===  ===
sed -i "s/#359bfa/#C094C0/g" *.svg

exit 0
